[package]
name = "zed-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zed-sdk-sys = { version = "0.1.0", path = "../zed-sdk-sys" }
